### PR TITLE
Chore signin 163407314

### PR DESCRIPTION
**Pull request by richien**
Kindly review this PR that integrates the signin route to the userdb_api

@HabibSentongo
 @Rhytah
@Mastula77
 @wasswa-derick

### CODE REVIEW

**Review by NicholusMuwonge — COMMENTED** [review]
Its quite a lot in one commit but it looks clean to me

**Comment by richien** [comment]
> 
> 
> Its quite a lot in one commit but it looks clean to me

Thanks for the feedback. There is a lot of refactoring of the route and of the tests hence the large commits, but this is noted and I will endeavor to do micro-commits.

**Comment by HabibSentongo** [comment]
yes as Nicholus already said, it's really a lot, but your work is well organized so it wasn't hard following up. Your route looks good enough to me.

**Comment by wasswa-derick** [comment]
@richien Lets ensure to have these TravisCI Builds passing.

**Pull request merged**
